### ISSUE TITLE
Can't access qri.io from IPFS gateway

### ISSUE THREAD

**Issue by etam** [qri-io/website#117]
I have IPFS companion installed, which redirects IPFS enabled sites to a local gateway.
Currently `dig TXT _dnslink.qri.io` returns `dnslink=/ipfs/QmPdCwtbBjGFp3bFnsuA1XYA9aaygYYnxkKu1Qj1XUERPq`. My node cannot download this content (downloading hangs forever).

**Comment by chriswhong** [comment]
Closing as stale, if you're still experiencing this issue, please open a new issue in [qri.io/qri](https://github.com/qri-io/qri)
