### ISSUE TITLE
404 page layout

### ISSUE THREAD

**Issue by chriswhong** [qri-io/website#141]
404 page layout has no container, text is pushed up against the left side:

![https___qri_io_foo](https://user-images.githubusercontent.com/1833820/73090800-0d310b80-3ea7-11ea-9de2-62ece0e93db6.png)

**Comment by mecm1993** [comment]
@chriswhong this `bug` is no longer happening after the following [commit](https://github.com/qri-io/website/commit/3c6b0d90d34a89e6b5ee712fcaaecda6684ad21f#diff-49c6932e6818612db33ae37fc36e214f).
