### ISSUE TITLE
Audit Meta Title and Meta Description Tags on all pages

### ISSUE THREAD

**Issue by chriswhong** [qri-io/website#146]
Let's make sure every last page has good title, meta.title, and meta.description.  

This is done with frontmatter on MD pages, and with <helmet> elements on JSX pages.

**Comment by mecm1993** [comment]
### Summary by file

**File**: `brooklyn-bus-times.md`
**Path**: `src/pages/data-stories/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|Tracking a Bus Route's Data Footprint|N/A |N/A |N/A |

**File**: `apply.js`
**Path**: `src/pages/jobs/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|-------------|--------------|-----------------------------|
|Apply to Jobs at Qri|Use this form to apply to open positions at Qri, Inc.|N/A |N/A |N/A |

**File**: `index.js`
**Path**: `src/pages/jobs/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|Jobs at Qri|A running list of job openings at Qri. Join our team! If you see it here, the job&apos;s still open.|N/A |N/A |N/A |

**File**: `job-backend-software-engineer.md`
**Path**: `src/pages/jobs/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |Qri Job Posting - Backend Software Engineer |N/A |

**File**: `job-data-research-assistant.md`
**Path**: `src/pages/jobs/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |Qri Job Posting - Data Research Assistant|N/A |

**File**: `job-frontend-software-engineer.md`
**Path**: `src/pages/jobs/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |Qri Job Posting - Frontend Software Engineer|N/A |

**File**: `privacy-policy.md`
**Path**: `src/pages/legal/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |Qri Privacy Policy|Qri Privacy Policy for Qri, Inc. |

**File**: `tos.md`
**Path**: `src/pages/legal/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |Qri Terms of Use|Terms of Use for software and services provided by Qri, Inc. |

**File**: `deterministic-querying.js`
**Path**: `src/pages/papers/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|Deterministic Querying |The current infrastructure that underlies the distribution and processing of data over the Internet has enabled dramatic advances in a wide variety of human activities. Recent trends promoting open data promise even greater benefits as the number and variety of networked datasets grow. However, while current technologies and architectures obviously do work, they also show signs of systemic inefficiencies that impede effective large-scale discovery, distribution, preservation and reuse of datasets. An important source of inefficiency is rooted in the database-centric architecture that underlies much of data processing on the Internet today. The transition to a content-addressed permanent web offers an opportunity to replace certain software architecture patterns with alternatives that are more efficient and scale more effectively. We introduce one such new pattern, deterministic querying, that combines formalized query definitions, formalized data descriptions, linked metadata, hashing, and a content-addressed file system. The result supports database-free reuse of data and data processing results—and can do so on the scale of the global Internet. |N/A |N/A |

**File**: `404.js`
**Path**: `src/pages/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|Not Found |You tried to load a page that doesn&apos;t exist |N/A |N/A |

**File**: `about.md`
**Path**: `src/pages/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |About Qri |Qri is leading an open-source project to build software for dataset synching, versioning, storing and collaboration. |

**File**: `beta.js`
**Path**: `src/pages/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|Qri Beta Program |Join the Qri beta program to try out new features |N/A |N/A |

**File**: `contact.md`
**Path**: `src/pages/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |Contact Qri|How to get in touch with Qri |

**File**: `docs.js`
**Path**: `src/pages/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|Qri Docs |Documentation for Qri Desktop and Qri CLI |N/A |N/A |

**File**: `download.js`
**Path**: `src/pages/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|Download Qri |Download Qri Desktop for Mac or Windows |N/A |N/A |

**File**: `faq.md`
**Path**: `src/pages/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |Frequently Asked Questions |Frequently Asked Questions about Qri |

**File**: `index-redesign.js`
**Path**: `src/pages/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |N/A |N/A |

**File**: `index.js`
**Path**: `src/pages/`
|Title | Description |MetaTitle            | MetaDescription                   |
|-----|------------|----------------|-----------------------------|
|N/A |N/A |N/A |N/A |

@chriswhong

**Comment by chriswhong** [comment]
Thanks so much for this @mecm1993, we will make use of this list the next time we do website updates to tidy things up.
