### ISSUE TITLE
docs: tutorial styling

### ISSUE THREAD

**Issue by osterbit** [qri-io/website#19]
So the content of the tutorial looks great but I think some visual/styling changes might improve usability including:
- [x] [codeblocks with syntax highlighting](https://gohugo.io/content-management/syntax-highlighting/)
- [ ] better overflow (as I make the window wider, to see more content, I just get a larger empty left margin

and less important but maybe still worth considering:
- [ ] if we want the entire thing on a single page, copying the table of contents into something like a scroll-nav might be helpful for finding your place

**Comment by chriswhong** [comment]
Closing as stale
