### ISSUE TITLE
transform docs should clarify that docs only execute once

### ISSUE THREAD

**Issue by b5** [qri-io/website#192]
Two examples of users tripping on this not being documented well enough:
[one](https://discordapp.com/channels/497052800778502152/580806684088336395/693341788970156063)

```
my initial transform I created the dataset from apparently was not part of the commit, didn't expect/realize this before
```

[two](https://discordapp.com/channels/497052800778502152/580806684088336395/689896730510229608)

```
I did a successful qri save with a transform. Next time I ran it, I get this error.
❯ qri save
name or bodypath is required
What that mean? What do I need to do to fix it?
```

We should add another set of steps to the transform tutorial that covers using `--recall` and why it exists.

**Comment by dustmop** [comment]
When we run `prepareDataset`, we always look up the previous version. One option is that, if we note that a previous version had a transform, but the next does not, *and* there's no changes, return a message that includes "use --recall to return your transform".

An additional problem in this report is that the user is running `qri save` with no reference, so it thinks they're trying to make a brand-new dataset (or running in an fsi working directory, but the terminal output doesn't indicate that). We could change the error message to be "no dataset reference given, saving a new dataset requires a name or a bodypath"

**Comment by b5** [comment]
into this. We should also clarify in docs that qri-io/qri#743 is the reason we don't auto-rerun transforms: rerunning automatically removes the capacity to make manual edits.
