### ISSUE TITLE
Page Up, Page Down, Home, and End keys don't work as expected

### ISSUE THREAD

**Issue by chriswhong** [qri-io/website#202]
From[ this thread on hackernews](https://news.ycombinator.com/item?id=22849232),  Page Up, Page Down, Home, and End keys don't work from Firefox 75.

**Comment by calroc** [comment]
Cheers! I usually browse with JS disabled, but I enabled it to check, and it still happens.
Up and down arrow keys also do not work.
  Scroll wheel works.
