### ISSUE TITLE
Starlark secrets example is incorrect

### ISSUE THREAD

**Issue by dustmop** [qri-io/website#212]
At: https://qri.io/docs/transforms/runtime

The description of how to provide secrets to a starlark script is incorrect. It says to use a dataset.yaml file with a `secrets:` field. However, the secrets field is transient and is not used. Instead, a user is supposed to run `qri save --file transform.star --secrets key,value`. The `--secrets` flag is not mentioned in the documentation.

The source file is at: content/docs/transforms/runtime.md

**Comment by feep** [comment]
### Current `qri help`

```
❯ qri version
0.9.10-dev

❯ qri help save
...
      --secrets strings   transform secrets as comma separated key,value,key,value,... sequence
...
```

**Comment by feep** [comment]
@dustmop, this content is largely duplicated in [`transforms/overview`](https://qri.io/docs/transforms/overview#context-argument-ctx).

Looks fine to have it both places, just checking.
