### ISSUE TITLE
Homepage links to Qri blog posts exclude images

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/website#228]
Looks like our 'data stories' banner is no longer presenting the cover images for our medium blog posts. 

<img width="739" alt="Screen Shot 2020-07-28 at 11 46 16 AM" src="https://user-images.githubusercontent.com/28312271/88689141-23bf5600-d0c8-11ea-86ba-8ea28b2ab5d3.png">

**Comment by feep** [comment]
The images are [still there](https://deploy-preview-222--qri-website.netlify.app/) (that’s the last deploy) they just don’t display.

Looks like #227 caused a stylesheet issue. Looking into it.
