### ISSUE TITLE
Add a CLI getting started page

### ISSUE THREAD

**Issue by b5** [qri-io/website#237]
### What feature or capability would you like?

A new page on our website: qri.io/cli that includes details for downloading qri CLI and QuickStart instructions

### Do you have a proposed solution?

General details the page should include:

* should say qri CLI is available for mac, windows & linux
* users can install via `curl`: `curl -fsSL https://qri.io/install.sh | sh`
* they can also download from our [GitHub releases page](https://github.com/qri-io/qri/releases)

**Quickstart**
Users should run the following to get started:
`$ qri setup`

`$ qri registry signup --email `YOUR_EMAIL`
_or, if you already have a qri.cloud account:_
`qri registry prove --email YOUR_EMAIL`

* add `--help` to any command for a detailed description of the command
* more info at qri.io/docs

Next link should be to docs

**Comment by feep** [comment]
From (private) [Discord](https://discord.com/channels/497052800778502152/713041013853126699/741020601145098271).
> rico:
> this already exists
> @b5 i mean, i'm all for promoting CLI to a direct subdomain as opposed to tucking it under docs, but maybe just make the page slicker/flashier, more welcoming, give it a hero & intro
> b5: exactly
> b5: I think we should just make the page flashier
> b5: and have a shorter link
