### ISSUE TITLE
Need to clarify Difference between Qri & Dat

### ISSUE THREAD

**Issue by b5** [qri-io/website#25]
This kinda sums up why this is important:
https://twitter.com/gozala/status/1034918186980847616

And this is definitely the first time I've had this question asked. We owe a proper description of how Qri & Dat are different. Long term, we need to put out an updated whitepaper that summarizes the project, but Let's get an FAQ going before then.

**Comment by RangerMauve** [comment]
Mind linking to where the change happened?

**Comment by b5** [comment]
Ah sorry this was a hasty drag-to-close from waffle. We ended up answering a slightly different question on our FAQ page (https://qri.io/faq/) that we get far more frequently: Dat vs. IPFS.  If you'd like a deeper dive on how Qri & Dat are different I'd be happy to discuss here @RangerMauve & we can work it into the site copy 😄. 

I'm a huge fan of the Dat project, in particular the delightful culture & values that members of the Dat community work so hard to keep in the foreground. If we can't yet support interop with Dat on a technical level, we can at least take inspiration from Dat on a cultural level, starting with a conversation about how the two projects are (technically) different, and could one day fall into a position of mutual support.

**Comment by RangerMauve** [comment]
Hey, just read the part about Dat in the README. I think it's actually a pretty good explanation for what the main differences are. I think that the other explanations of how Qri work help with the other details. :D
