### ISSUE TITLE
Landing Page Blobs Blurry and cut off laterally

### ISSUE THREAD

**Issue by chriswhong** [qri-io/website#345]
Let's get a higher resolution image or an SVG

**Comment by tefyzambrano** [comment]
![Main-Img](https://user-images.githubusercontent.com/85688198/143214833-321c2191-a2e5-40f9-a9b2-8d59d3b8a52f.png)

**Comment by tefyzambrano** [comment]
<img width="701" alt="Screenshot 2021-11-24 at 10 51 12" src="https://user-images.githubusercontent.com/85688198/143215211-da1ca917-ae67-4ebb-8525-13d147702505.png">
