### ISSUE TITLE
Downloading QRI is 404'ing

### ISSUE THREAD

**Issue by shapironick** [qri-io/website#67]
Hi dears, was just trying to get a sneaky peek and download the latest version of the desktop. 
When i click the download link on http://qri.io/download/ I am lead to this link 
https://github.com/qri-io/qri/releases/download/v0.6.1/qri_os_x_cli_darwin_amd64.pkg which 404s

My R skills are not even good enough to use QRI yet so this is actually for the best!

**Comment by b5** [comment]
Ah! Thanks so much for the heads up @shapironick! We just updated the site, and this should now be fixed. I'll close this, but if you're still seeing 404's, post on this closed issue & we'll investigate further.
