### ISSUE TITLE
Documentation Roadmap:

### ISSUE THREAD

**Issue by ramfox** [qri-io/website#83]
IN PROGRESS ISSUE

Qri is a complex tool with a multitude of features and many use cases. We need to do a better job of documenting them. This issue is intended as a roadmap for our first coordinated push to bettering our documentation.

There are three sections we want to focus on and what they currently contain:
1) Tutorials - the how-tos of qri
   - intro to the cmd
   - link to frontend videos
2) Reference - the syntax and apis
  - __starlark examples__: a starlark in qri overview (I think this used to be in tutorials, why the change?)
  - __starlark qri & ds modules__: the qri and ds modules api
  - __starlark standard library__: the standard library api
  - __CLI commands__: a list of all the cli commands
  - __Dataset__: the basic dataset api
  - __Starlark language__: an overview of the starlark language itself
  - __html templates__: coming soon
3) Workflows - some examples of how folks might use qri 
  - page does not yet exist

Reference:
Api
config
viz templates

Workflows:
export to excel
edit to diff to publish
remotes

**Comment by chriswhong** [comment]
Closing as stale, top-level docs categories were recently updated, will make new issues for expanding docs.
