### ISSUE TITLE
Suggestion: re-orient docs menu triangles

### ISSUE THREAD

**Issue by Frijol** [qri-io/website#89]
I'm finding these little triangles really unintuitive:

![Screen Shot 2019-06-07 at 1 32 26 PM](https://user-images.githubusercontent.com/454690/59131980-b9c67900-8928-11e9-9def-e9b90305f6ed.png)

Other design paradigms I've seen have the triangle pointing down *when the menu is already open*, which initially made me think that since the triangles were pointing down on all the sections, there might be no content there.

This is more what I expected to see for a closed menu:

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313332363439382f313731363232372f64363661303765302d363162642d313165332d393531362d6435643862653538316631642e706e67](https://user-images.githubusercontent.com/454690/59132109-1cb81000-8929-11e9-94da-b25ecf16e95d.png)

**Comment by chriswhong** [comment]
Closing as no longer relevant, there are no longer menu triangles
